version: '2.0'

services:
    db:
        image: mysql:5.7
        volumes:
            - database:/var/lib/mysql
        restart: always
        environment:
          MYSQL_DATABASE: "eve_universe"
          MYSQL_USER: "${MYSQL_USER}"
          MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    pathfinder:
        image: kryptedgaming/pathfinder
        env_file: .env
        ports:
            - "8000:80"

volumes:
    database: {}
