version: '2.0'

services:
    db:
        image: mysql:5.7
        volumes:
            - database:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pathfinder
    pathfinder:
        build: .
        ports:
            - "8000:80"

volumes:
    database: {}
